name: label_printer
description: Print image, label with flutter bitmap_printer
version: 0.0.2
homepage: https://github.com/ngthminhdev/label_printer


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
